### PR TITLE
feat(graphql,rest): add faster CORS headers

### PR DESCRIPTION
**Pull request by damienwebdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/magento2-cors/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Fixes: #65 

## What is the new behavior?
The layer in which we compute whether or not an incoming preflight request receives CORS headers has changed. Previously, we leveraged a plugin around the relevant native Magento 2 Controller (webapi_rest/graphql) and as a result, we incurred significant overhead from Magento code when computing CORS headers. 

In the new code we no longer incur this overhead by adding a plugin around application launch and creating our own custom controller. It is **very possible** that we broke expectations of anything that plugs-in around this plugin or adds additional CORS headers other than our own. 

For 99.99% of GraphQl/Rest API deployments, the API is used sessionlessly. As such, we can take the opportunity to improve performance for the majority at the expense of the minority. If this breaks your codebase, please submit an issue and we will see what can be done to remedy your specific use-case.

In theory, most dependents simply need to upgrade and there are no breaking changes. 

**However,** if you were expecting to use the native GraphQl/REST controller when computing CORS headers (and everything else that entails - like having a Magento session, for example) that guarantee is no-longer provided.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information

### CODE REVIEW

**Comment by fooman** [comment]
I vaguely remember seeing a similar discussion for Magento core, ie should the body of the request get processed for an OPTIONS request. I think it was then decided to indeed render the body as the headers for the OPTIONS request can/may include the response size - not sure if that is the right approach for HTTP or not. Let me see if I can find that discussion.

**Comment by fooman** [comment]
This was the comment I remembered https://github.com/magento/magento2/issues/21299#issuecomment-469214846

**Comment by damienwebdev** [comment]
@fooman I've been running this in production for a while with very good performance results and no resulting issues. 

Considering that the real request is made anyways, I didn't see an issue.

I've left this open, unmerged because I'm not certain the resulting behavior is *precisely* correct and may be breaking for some users.

The performance gain is substantial however. I was averaging ~20ms responses on a 1 vCPU vm in azure with a warm opcache but no Varnish.

Most of the perf hit came from application boostrap.

**Comment by damienwebdev** [comment]
I'll add a diff to support the Content-Length (though I wonder if this is already calculated by Nginx).

**Comment by fooman** [comment]
Tested this out in our development environment and so far looks great.

**Comment by damienwebdev** [comment]
@fooman any chance you could throw an `ab` at it and post the results (along with VM size)?

**Comment by fooman** [comment]
@damienwebdev can't isolate it easily at the moment but here is the best I can do for a comparison. 

```
  Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:      606  619   8.2    618     649
Processing:   298  340  37.1    334     459
Waiting:      297  340  37.1    334     459
Total:        909  958  38.5    951    1084



Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:      602  618  10.1    617     660
Processing:   220  239  10.3    239     274
Waiting:      220  238  10.3    238     274
Total:        834  857  12.5    857     889
```

It is against a monolithic test instance with 4GB but it is sitting across a big body of water on the opposite side of the world.

**Comment by damienwebdev** [comment]
@fooman awesome thanks so much!

**Pull request merged**
